import java.util.*;
public class Vivek_loves_Array_Game {
    // from CB
    /*
        Divide the array in two non-empty parts such that sum of both these contigious parts is equal.
        On each successfull partition score increases by 1.
        For any unsuccessfull division the game ends..

        Find the maximum score can be generated by Vivek.
     */
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int n = sc.nextInt();
        int [] arr = new int[n];
        for(int i = 0 ; i < arr.length ; i++){
            arr[i] = sc.nextInt();
        }
        int score = Divide(arr,0,arr.length-1);
        System.out.println(score);
    }    
    public static int Divide(int [] arr, int si, int ei){
        for(int mid = si; mid < ei ; mid++){
            int sum1 = 0;
            for(int i = si; i <= mid ; i++){
                sum1 += arr[i];
            }
            int sum2 = 0;
            for(int i = mid+1; i <= ei; i++){
                sum2 += arr[i];
            }
            if(sum1 == sum2){
                int f = Divide(arr,si,mid);
                int s = Divide(arr,mid+1,ei);
                return Math.max(f,s)+1;     // Dono ka max + apna wala jiska sum equal aaya hai..
            }
        }
        return 0;
    }
}
